"use client";

import { columns, Transaction } from "@/app/components/transactions/columns";
import { DataTable } from "@/app/components/transactions/data-table";
//TODO: IMPORT ASSETS

const data: Transaction[] = [
  {
    id: "1",
    name: "Emma Richardson",
    avatar: "/assets/images/avatars/emma-richardson.jpg",
    category: "General",
    date: "2024-08-19T14:23:11Z",
    amount: 75.5,
    recurring: false,
  },
  {
    id: "2",
    name: "Savory Bites Bistro",
    avatar: "/assets/images/avatars/savory-bites-bistro.jpg",
    category: "Dining Out",
    date: "2024-08-19T20:23:11Z",
    amount: -55.5,
    recurring: false,
  },
  {
    id: "3",
    name: "Luna Yoga Studio",
    avatar: "/assets/images/avatars/luna-yoga.jpg",
    category: "Wellness",
    date: "2024-08-20T08:10:00Z",
    amount: -40,
    recurring: true,
  },
  {
    id: "4",
    name: "Bright Groceries",
    avatar: "/assets/images/avatars/bright-groceries.jpg",
    category: "Groceries",
    date: "2024-08-20T10:15:30Z",
    amount: -85.75,
    recurring: false,
  },
  {
    id: "5",
    name: "Side Hustle Payout",
    avatar: "/assets/images/avatars/side-hustle.jpg",
    category: "General",
    date: "2024-08-21T18:45:00Z",
    amount: 200,
    recurring: false,
  },
  {
    id: "6",
    name: "Streamify Subscription",
    avatar: "/assets/images/avatars/streamify.jpg",
    category: "Bills",
    date: "2024-08-22T00:00:00Z",
    amount: -12.99,
    recurring: true,
  },
  {
    id: "7",
    name: "Cafe Bloom",
    avatar: "/assets/images/avatars/cafe-bloom.jpg",
    category: "Dining Out",
    date: "2024-08-22T11:25:00Z",
    amount: -8.5,
    recurring: false,
  },
  {
    id: "8",
    name: "Freelance Payment",
    avatar: "/assets/images/avatars/freelance.jpg",
    category: "General",
    date: "2024-08-23T09:00:00Z",
    amount: 400,
    recurring: false,
  },
  {
    id: "9",
    name: "Bright Groceries",
    avatar: "/assets/images/avatars/bright-groceries.jpg",
    category: "Groceries",
    date: "2024-08-23T17:30:00Z",
    amount: -76.25,
    recurring: false,
  },
  {
    id: "10",
    name: "Gym Membership",
    avatar: "/assets/images/avatars/gym.jpg",
    category: "Wellness",
    date: "2024-08-24T07:00:00Z",
    amount: -49.99,
    recurring: true,
  },
  {
    id: "11",
    name: "Bento Sushi",
    avatar: "/assets/images/avatars/bento-sushi.jpg",
    category: "Dining Out",
    date: "2024-08-24T13:40:00Z",
    amount: -22.4,
    recurring: false,
  },
  {
    id: "12",
    name: "Coffee Collective",
    avatar: "/assets/images/avatars/coffee-collective.jpg",
    category: "Dining Out",
    date: "2024-08-25T08:30:00Z",
    amount: -5,
    recurring: false,
  },
  {
    id: "13",
    name: "Electric Utility",
    avatar: "/assets/images/avatars/electric.jpg",
    category: "Bills",
    date: "2024-08-25T12:00:00Z",
    amount: -60.25,
    recurring: true,
  },
  {
    id: "14",
    name: "Emma Richardson",
    avatar: "/assets/images/avatars/emma-richardson.jpg",
    category: "General",
    date: "2024-08-25T15:30:00Z",
    amount: 125,
    recurring: false,
  },
  {
    id: "15",
    name: "Whole & Fresh",
    avatar: "/assets/images/avatars/whole-fresh.jpg",
    category: "Groceries",
    date: "2024-08-26T10:10:00Z",
    amount: -98.75,
    recurring: false,
  },
  {
    id: "16",
    name: "Spotify Premium",
    avatar: "/assets/images/avatars/spotify.jpg",
    category: "Bills",
    date: "2024-08-26T00:00:00Z",
    amount: -9.99,
    recurring: true,
  },
  {
    id: "17",
    name: "Uber Ride",
    avatar: "/assets/images/avatars/uber.jpg",
    category: "Transport",
    date: "2024-08-26T21:15:00Z",
    amount: -13.2,
    recurring: false,
  },
  {
    id: "18",
    name: "Transfer In",
    avatar: "/assets/images/avatars/transfer.jpg",
    category: "General",
    date: "2024-08-27T16:00:00Z",
    amount: 300,
    recurring: false,
  },
  {
    id: "19",
    name: "Savory Bites Bistro",
    avatar: "/assets/images/avatars/savory-bites-bistro.jpg",
    category: "Dining Out",
    date: "2024-08-27T19:45:00Z",
    amount: -58.5,
    recurring: false,
  },
  {
    id: "20",
    name: "Freelance Payment",
    avatar: "/assets/images/avatars/freelance.jpg",
    category: "General",
    date: "2024-08-28T11:15:00Z",
    amount: 250,
    recurring: false,
  },
  {
    id: "21",
    name: "Netflix Subscription",
    avatar: "/assets/images/avatars/netflix.jpg",
    category: "Bills",
    date: "2024-08-28T00:00:00Z",
    amount: -15.49,
    recurring: true,
  },
  {
    id: "22",
    name: "Local Farmers Market",
    avatar: "/assets/images/avatars/farmers.jpg",
    category: "Groceries",
    date: "2024-08-28T09:30:00Z",
    amount: -32.4,
    recurring: false,
  },
  {
    id: "23",
    name: "Trek Bikes",
    avatar: "/assets/images/avatars/trek.jpg",
    category: "Transport",
    date: "2024-08-29T14:00:00Z",
    amount: -120,
    recurring: false,
  },
  {
    id: "24",
    name: "Emma Richardson",
    avatar: "/assets/images/avatars/emma-richardson.jpg",
    category: "General",
    date: "2024-08-29T17:00:00Z",
    amount: 175.5,
    recurring: false,
  },
  {
    id: "25",
    name: "Cafe Bloom",
    avatar: "/assets/images/avatars/cafe-bloom.jpg",
    category: "Dining Out",
    date: "2024-08-30T10:00:00Z",
    amount: -9.25,
    recurring: false,
  },
  {
    id: "26",
    name: "Luna Yoga Studio",
    avatar: "/assets/images/avatars/luna-yoga.jpg",
    category: "Wellness",
    date: "2024-08-30T07:30:00Z",
    amount: -40,
    recurring: true,
  },
  {
    id: "27",
    name: "Bright Groceries",
    avatar: "/assets/images/avatars/bright-groceries.jpg",
    category: "Groceries",
    date: "2024-08-30T16:30:00Z",
    amount: -90.3,
    recurring: false,
  },
  {
    id: "28",
    name: "Freelance Payment",
    avatar: "/assets/images/avatars/freelance.jpg",
    category: "General",
    date: "2024-08-31T11:45:00Z",
    amount: 275,
    recurring: false,
  },
  {
    id: "29",
    name: "Gas Station",
    avatar: "/assets/images/avatars/gas.jpg",
    category: "Transport",
    date: "2024-08-31T18:20:00Z",
    amount: -43.75,
    recurring: false,
  },
  {
    id: "30",
    name: "Streamify Subscription",
    avatar: "/assets/images/avatars/streamify.jpg",
    category: "Bills",
    date: "2024-08-31T00:00:00Z",
    amount: -12.99,
    recurring: true,
  },
];

const TransactionsPage = () => {
  return (
    <div className="flex flex-col h-full p-4 space-y-4">
      {/* Header */}
      <div className=" ">
        <h2 className="text-preset-1">Transactions</h2>
      </div>

      {/* Table Container */}
      <div className="bg-white rounded-lg w-[1000px] p-4  ">
        <DataTable columns={columns} data={data} />
      </div>
    </div>
  );
};

export default TransactionsPage;
